version: "3.2"
services:
  # The zipkin process services the UI, and also exposes a POST endpoint that
  # instrumentation can send trace data to.
  zipkin:
    image: ghcr.io/openzipkin/zipkin-slim:${TAG:-latest}
    container_name: zipkin
    # Environment settings are defined here https://github.com/openzipkin/zipkin/blob/master/zipkin-server/README.md#environment-variables
    environment:
      - STORAGE_TYPE=mem
      # Uncomment to enable self-tracing
      # - SELF_TRACING_ENABLED=true
      # Uncomment to increase heap size
      # - JAVA_OPTS=-Xms128m -Xmx128m -XX:+ExitOnOutOfMemoryError
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - 9411:9411
    # Uncomment to enable debug logging
    # command: --logging.level.zipkin2=DEBUG
    networks:
      - elk-net 
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:${TAG:-7.17.16}
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - "transport.host=127.0.0.1"
      - "http.host=0.0.0.0"
    networks:
      - elk-net
    ports:
      - 19200:9200
  logstash:
    container_name: ls-container
    image: docker.elastic.co/logstash/logstash:${TAG:-7.17.16}
    environment:
      - xpack.security.enabled=false
    command: logstash -e 'input { tcp { port => 5001 codec => "json" }} output { elasticsearch { hosts => "elasticsearch:9200" index => "modern-api" }}'
    networks:
      - elk-net
    depends_on:
      - elasticsearch
    ports:
      - 5002:5001
  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:${TAG:-7.17.16}
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200 
    networks:
      - elk-net
    depends_on:
      - elasticsearch
    ports:
      - 5600:5601
  apm:
    container_name: apm-container
    image: docker.elastic.co/apm/apm-server:${TAG:-7.17.16}
    ports:
    - "8200:8200"
    - "6060:6060"
    networks: ['elk-net']
    depends_on: ['elasticsearch'] 
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200 
    command: >
      apm-server -e
        -E apm-server.rum.enabled=true
        -E apm-server.rum.event_rate.limit=1000
        -E setup.kibana.host=["kb-container:5601"]
        -E apm-server.kibana.enabled=true
networks:
  elk-net:
    driver: bridge
